### ISSUE TITLE
Help Needed - Retrieving Media Files In motion-gosu Project

### ISSUE THREAD

**Issue by ghost** [gosu/motion-gosu#5]
I'm finding that I'm unable to retrieve media files in my project.

The directory structure of my project goes as follows:

```
> Kuku
     > app
          > window.rb
     > resources
          > sky.png
```

I'm trying to `initialize` the sky.png image in the window.rb file using `@background = Gosu::Image.new('../resources/sky.png')` but I get a `cannot open sky.png` error message. Thought it might be related to me trying to go back a directory in the previous attempt, so tried `@background = Gosu::Image.new('resources/sky.png')` and `@background = Gosu::Image.new('~/resources/sky.png')` with no luck. 

Not sure if I'm missing something basic here, but any help will be much appreciated!

Thanks.

**Comment by jlnr** [comment]
I've just checked what I did in my unfinished Trikus game, and it involved changing the current directory in the App Delegate: https://github.com/jlnr/Trikus/blob/master/ios/app/app_delegate.rb

Does this work for you? I'll try to provide a cleaner motion-gosu example project soon.

**Comment by ghost** [comment]
Yes, the above has worked for me.

Thanks.
