### ISSUE TITLE
Bug Fix Needed? - motion-gosu Gosu::Image (NameError)

### ISSUE THREAD

**Issue by ghost** [gosu/motion-gosu#7]
Hi,

I'm running motion-gosu along with RubyMotion.

When I build my project to run on Xcode's iPhone 6s simulator, the simulator starts but then crashes and I get this error message:

/Users/Nitish/.rvm/gems/ruby-2.4.0/bundler/gems/motion-gosu-49f95f74b87c/motion/image.rb:18:in `<ma: undefined method `from_text' for class `Gosu::Image' (NameError)

There seems to be an issue with the `from_text` method from the Gosu::Image class?

Any help would be appreciated.

Thanks.

**Comment by jlnr** [comment]
Closing this since a clean build has apparently solved the problem :)
