### ISSUE TITLE
Help Needed - Google Ads Mobile Integration With motion-gosu

### ISSUE THREAD

**Issue by ghost** [gosu/motion-gosu#8]
Hi, 

I've been trying to implement GoogleMobileAds into an iOS app I've been developing using RubyMotion `motion-gosu`. I've implemented the part that allows the interstitial type Google ad to be created and loaded, but I've been having problems trying to get the ad to actually appear on the screen. The console states that the ad is displaying itself onto the screen, but the screen is not actually showing the ad.

I've been following these guides to implement the interstitial ad:
https://developers.google.com/admob/ios/quick-start
https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/admob/InterstitialExample/InterstitialExample/ViewController.m

The method I've created to create and load the interstitial ad goes as follows:

```
def create_and_load_interstitial
    @interstitial = GADInterstitial.alloc.initWithAdUnitID('ca-app-pub-3940256099942544/4411468910')
    request = GADRequest.request()
    request.testDevices = ['device_id']
    @interstitial.loadRequest(request)
end
```

By looking at the **GADInterstitial.h** file, the method that would allow me to display the interstitial ad after it has been created and loaded is this method:

```
/// Presents the interstitial ad which takes over the entire screen until the user dismisses it.
/// This has no effect unless isReady returns YES and/or the delegate's interstitialDidReceiveAd:
/// has been received.
///
/// Set rootViewController to the current view controller at the time this method is called. If your
/// application does not use view controllers pass in nil and your views will be removed from the
/// window to show the interstitial and restored when done. After the interstitial has been removed,
/// the delegate's interstitialDidDismissScreen: will be called.
- (void)presentFromRootViewController:(nonnull UIViewController *)rootViewController;
```

And so the code I tried was:

```
if @interstitial.isReady
     @interstitial.presentFromRootViewController(self)
else
     puts "Ad wasn't ready."
end
```

**self** in the code above represents **Window < Gosu::Window**

The **present** method above states that if there aren't any view controllers that are being used, then pass in **nil**. I'm not quite sure how this works in conjunction with the motion-gosu development framework as **draw** needs to be used to actually get something to appear on the screen.

Any help with this will be much appreciated. Thanks in advance.

**Comment by jlnr** [comment]
Gosu::Window is neither a UIViewController nor a UIWindow, so it cannot be passed directly.

I haven't touched this code in a bit, but in the [example AppDelegate](https://github.com/gosu/motion-gosu/blob/master/example/ios/app/app_delegate.rb), it looks like `Gosu::Window#uikit_window` returns the UIWindow, and `self.uikit_window.rootViewController` should give you a UIViewController from which you can present the interstitial.

Does that work?

**Comment by jlnr** [comment]
Out of curiosity, what happens if you pass `nil`? Everything *inside* Gosu::Window needs to be drawn in `#draw`, but other views can still be drawn on top of it, so it might just work.

**Comment by ghost** [comment]
I changed my app_delegate.rb file to match your example and passed through `self.uikit_window.rootViewController` and the interstitial ad is now displaying 👍

**Comment by ghost** [comment]
I tried passing in `nil` and the same issue occurred in that the console was saying the ad is showing when it actually wasn't showing anything.

**Comment by jlnr** [comment]
I'll close this since the explicit way works.
